#!/usr/bin/env python3

'''
input:  alignment file as BAM file
output: consensus sequences including either the majority base or the ambiguous
        bases as FASTA files
'''

import pysam
import argparse
import os
import numpy as np
from Bio import SeqIO
from Bio.SeqRecord import SeqRecord
from Bio.Seq import Seq
from smallgenomeutilities.__checkPath__ import CheckPath
from smallgenomeutilities.__pileup__ import get_counts

__author__ = "Susana Posada Cespedes"
__copyright__ = "Copyright 2017"
__credits__ = "Susana Posada Cespedes"
__license__ = "GPL2+"
__maintainer__ = "Susana Posada Cespedes"
__email__ = "v-pipe@bsse.ethz.ch"
__status__ = "Development"


def parse_args():
    """ Set up the parsing of command-line arguments """
    parser = argparse.ArgumentParser(
            description="Script to construct consensus sequences",
            formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    requiredNamed = parser.add_argument_group('required named arguments')
    requiredNamed.add_argument(
        "-i", required=True, metavar='BAM', dest='bamfile',
        help="Input BAM file"
    )
    parser.add_argument(
        "-f", required=False, metavar='FASTA', dest='reference', type=str,
        help="Fasta file containing the reference sequence"
    )
    parser.add_argument(
        "-r", required=False, default=None, metavar='BED', dest='region',
        type=str,
        help="Region of interested in BED format, e.g. HXB2:2253-3869. Loci "
             "are interpreted using 0-based indexing, and a half-open "
             "interval is used, i.e, [start:end)"
    )
    parser.add_argument(
        "-c", required=False, default=50, metavar='INT', dest='min_coverage',
        type=int, help="Minimum read depth for reporting variants per locus"
    )
    parser.add_argument(
        "-q", required=False, default=15, metavar='INT', dest='qual_thrd',
        type=int,
        help="Minimum phred quality score a base has to reach to be counted"
    )
    parser.add_argument(
        "-a", required=False, default=0.05, metavar='FLOAT', dest='min_freq',
        type=float, help="Minimum frequency for an ambiguous nucleotide"
    )
    parser.add_argument(
        "-n", required=False, default=None, metavar='INT', dest='n_threshold',
        type=int, help="Read count below which ambiguous base 'n' is reported"
    )
    parser.add_argument(
        "-N", required=False, default="CONSENSUS", type=str, metavar='STR',
        dest="sampleID", help="Patient/sample identifier"
    )
    parser.add_argument(
        "-o", required=False, default=os.getcwd(), action=CheckPath,
        metavar='PATH', dest='outdir', help="Output directory"
    )

    return parser.parse_args()


def majority_vote(counts, cov_thrd, alphabet):
    majority = np.argmax(counts, 0)
    cons_majority = alphabet[majority]

    return cons_majority, majority


def ambiguous_bases(counts, min_freq, majority=None):
    """
    counts: nucleotide counts per locus. Columns correspond to loci and rows to
    nucleotides A, C, G, T and deletions, in this order.
    """
    # Mapping {1: 'T', 2:'G', 3:'K', 4:'C', 5:'Y', 6:'S', 7:'B', 8:'A', 9:'W',
    #          10:'R', 11:'D', 12:'M', 13:'H', 14:'V', 15:'N'}
    IUPAC_CODE = np.array(('n', 'T', 'G', 'K', 'C', 'Y', 'S', 'B', 'A', 'W',
                           'R', 'D', 'M', 'H', 'V', 'N'))
    coverage = np.sum(counts, 0)
    # To report ambiguous bases, every base with a relative frequency greater
    # or equal to min_freq is accounted for. But at least two reads should
    # support that base
    min_count = np.ceil(min_freq * coverage)
    min_count[min_count <= 1] = 2
    aux = counts >= min_count
    aux = aux.astype(int)
    encoding = np.array((8, 4, 2, 1))
    for idx, val in enumerate(encoding):
        aux[idx, aux[idx, :] == 1] = val
    cons_ambig = IUPAC_CODE[np.sum(aux[:4, ], 0)]

    # Take into account deletions, when information is available
    if counts.shape[0] > 4:
        assert majority is not None
        cons_ambig[np.logical_and(majority == 4, aux[4, :] == 1)] = '-'

    return cons_ambig


def mask_low_quality(consensus, read_count, min_coverage, n_threshold,
                     reference=None, reference_name=None, start=None,
                     end=None):
    mask = read_count < min_coverage
    aux = np.char.lower(consensus[mask])
    consensus[mask] = aux

    if n_threshold is None:
        # Handle positions with zero read-count
        mask = read_count == 0
        if reference is None:
            consensus[mask] = 'n'
        else:
            reference = pysam.FastaFile(reference)
            assert reference.references[0] == reference_name, (
                "the name of the genomic region and the reference differ")
            reference = reference.fetch(
                reference=reference_name, start=start, end=end).lower()
            aux = [reference[idx] for idx in range(len(reference)) if mask[idx]]
            consensus[mask] = aux
    else:
        mask_n = read_count < n_threshold
        consensus[mask_n] = 'n'

    return consensus


def main():
    alphabet = np.array(['A', 'C', 'G', 'T', '-'])
    args = parse_args()

    reference_name = None
    if args.region is not None:
        aux = args.region.split(":")
        reference_name = aux[0]
        sampleID = ':'.join((args.sampleID, aux[1]))
        aux = aux[1].split('-')
        start = int(aux[0])
        end = int(aux[1])
    else:
        start = None
        end = None
        sampleID = args.sampleID

    # 1. Load BAM file and get counts per loci
    with pysam.AlignmentFile(args.bamfile, 'rc' if os.path.splitext(args.bamfile)[1] == '.cram' else 'rb') as alnfile:
        if reference_name is None:
            reference_name = alnfile.references[0]
        counts = alnfile.count_coverage(
            contig=reference_name, start=start, stop=end,
            quality_threshold=args.qual_thrd)
        counts = np.array(counts)

        # Account for deletions w.r.t reference
        region_len = counts.shape[1]
        alphabet_len = alphabet.size
        counts_dels = get_counts([
            args.bamfile, reference_name, start, end, region_len, alphabet_len
        ])
        counts_dels = counts_dels.reshape((alphabet_len, region_len), order='F')

    # 2. Build majority consensus
    cons_majority, majority_idx = majority_vote(
        counts, args.min_coverage, alphabet)
    cons_majority_dels, majority_idx = majority_vote(
        counts_dels, args.min_coverage, alphabet)

    # 3. Build consensus including ambiguous bases
    cons_ambig = ambiguous_bases(counts, args.min_freq)
    cons_ambig_dels = ambiguous_bases(counts_dels, args.min_freq, majority_idx)

    # 4. Mask positions with low coverage
    read_count = np.sum(counts, 0)
    read_count_dels = np.sum(counts_dels, 0)

    cons_majority = mask_low_quality(
        cons_majority, read_count, args.min_coverage, args.n_threshold,
        reference=args.reference, reference_name=reference_name, start=start,
        end=end)
    cons_majority_dels = mask_low_quality(
        cons_majority_dels, read_count_dels, args.min_coverage,
        args.n_threshold, reference=args.reference,
        reference_name=reference_name, start=start, end=end)
    cons_ambig = mask_low_quality(
        cons_ambig, read_count, args.min_coverage, args.n_threshold,
        reference=args.reference, reference_name=reference_name, start=start,
        end=end)
    cons_ambig_dels = mask_low_quality(
        cons_ambig_dels, read_count_dels, args.min_coverage, args.n_threshold,
        reference=args.reference, reference_name=reference_name, start=start,
        end=end)

    # 4. Write to output
    cons_majority = SeqRecord(
        Seq(''.join(cons_majority)), id=sampleID,
        description="| Majority-vote rule")
    cons_ambig = SeqRecord(Seq(''.join(cons_ambig)),
                           id=sampleID, description="| Ambiguous bases")

    cons_majority_dels = SeqRecord(
        Seq(''.join(cons_majority_dels)), id=sampleID,
        description="| Majority-vote rule")
    cons_ambig_dels = SeqRecord(
        Seq(''.join(cons_ambig_dels)), id=sampleID,
        description="| Ambiguous bases")

    with open(os.path.join(args.outdir, "ref_majority.fasta"), "w") as outfile:
        SeqIO.write(cons_majority, outfile, "fasta")

    with open(os.path.join(args.outdir, "ref_ambig.fasta"), "w") as outfile:
        SeqIO.write(cons_ambig, outfile, "fasta")

    with open(os.path.join(args.outdir, "ref_majority_dels.fasta"),
              "w") as outfile:
        SeqIO.write(cons_majority_dels, outfile, "fasta")

    with open(os.path.join(args.outdir, "ref_ambig_dels.fasta"),
              "w") as outfile:
        SeqIO.write(cons_ambig_dels, outfile, "fasta")


if __name__ == '__main__':
    main()
